### ISSUE TITLE
BLE device not detected after reboot in attach() despite successful reconnection

### ISSUE THREAD

**Issue by lenovo-li** [fwupd/fwupd#10862]
### Environment
- fwupd version: main branch (5d660d3ea)
- Device: Lenovo BLE mouse (VID 17EF, PID 629A)
- Command: `fwupdtool install <cab> --allow-older`

### Problem
BLE firmware update fails with:
```
failed to attach: failed to wait for attach replug: device 2d9af8a789b80c9891a2578467cc9e77b72c384a did not come back
```

The device successfully reboots and reconnects (confirmed by independent D-Bus monitor), but fwupd doesn't detect it.

### Plugin code
```c
static gboolean
fu_lenovo_accessory_ble_device_attach(FuDevice *device, FuProgress *progress, GError **error)
{
    FuLenovoAccessoryBleDevice *self = FU_LENOVO_ACCESSORY_BLE_DEVICE(device);

    /* release notify_io before device reboot */
    if (self->notify_io != NULL) {
        g_object_unref(self->notify_io);
        self->notify_io = NULL;
    }

    if (!fu_lenovo_accessory_impl_dfu_exit(FU_LENOVO_ACCESSORY_IMPL(device),
                                           FU_LENOVO_ACCESSORY_DFU_EXIT_CODE_DFU_SUCCESS,
                                           error)) {
        g_prefix_error_literal(error, "failed to exit: ");
        return FALSE;
    }
    fu_device_add_flag(device, FWUPD_DEVICE_FLAG_WAIT_FOR_REPLUG);
    return TRUE;
}
```

Device extends `FuBluezDevice`, sets `remove_delay` to 10000 ms in `init()`.

Full code: https://github.com/lenovo-li/fwupd/tree/feature/quirk-configurable-interface/plugins/lenovo-accessory

### Log output

**Coldplug (works):**
```
12:32:24.059 FuBackend BlueZ device /org/bluez/hci0/dev_E3_8A_43_0E_F1_2A: connected=1 paired=1 services_resolved=1 suitable=1
12:32:24.204 FuPluginLenovoAccessory BLE setup: device_id=2d9af8a789b80c9891a2578467cc9e77b72c384a physical_id=/org/bluez/hci0 logical_id=E3:8A:43:0E:F1:2A wait_for_replug=0
```

**Attach (device reboots):**
```
12:33:32.507 FuPluginLenovoAccessory BLE attach: device_id=2d9af8a789b80c9891a2578467cc9e77b72c384a physical_id=/org/bluez/hci0 logical_id=E3:8A:43:0E:F1:2A
12:33:32.521 FuPluginLenovoAccessory BLE attach: dfu_exit sent, device will reboot and reconnect
[10 seconds pass]
failed to attach: failed to wait for attach replug: device did not come back
```

No `BlueZ device` property-changed logs appear after `attach()`, and `BLE setup` is never called a second time.

**External monitor confirms BlueZ sees the reconnection:**
```
[20:28:37.066] Connected=0 ServicesResolved=0
[20:28:39.307] Connected=1
[20:28:39.842] ServicesResolved=1
```

The device returns with the same device_id, physical_id, and logical_id.

### Question
Why doesn't fwupd detect the BLE device after it reboots and reconnects? Is there something specific needed for BLE replug detection that differs from USB?

USB devices in the same plugin work fine with the same `WAIT_FOR_REPLUG` approach.

**Comment by hughsie** [comment]
> Is there something specific needed for BLE replug detection that differs from USB?

The bluetooth devices are enumerated by the bluez backend, not the udev backend. Does fwupd not get anything from the blues backend on reconnect? Could the device take longer than 10 seconds to reboot (and for bluez to reconnect to it)?  Does the device perhaps need re-pairing before it shows back up in bluez? e.g. what does `bluetoothctl` say?

**Comment by lenovo-li** [comment]
Thanks — answering your questions, and it turns out this is a regression in fwupd rather than something specific my plugin needs.

Test command (either device):

```
fwupdtool install ../fw/Lenovo-mouse_62f5-vs1.0.7.cab --allow-older
fwupdtool install ../fw/Lenovo-mouse_629a-vs0.0.18.cab --allow-older
```

**1. Does fwupd get anything from the bluez backend on reconnect?**

The D-Bus messages arrive in the process, but the per-proxy `g-properties-changed` handler connected in `fu_bluez_backend_object_added()` is never invoked. I confirmed this by subscribing to the raw signal on the object manager own `GDBusConnection`, bypassing the proxy layer:

```
[RAW] .../dev_E3_8A_43_0E_F1_2A: ServicesResolved=false
[RAW] .../dev_E3_8A_43_0E_F1_2A: Connected=false
[RAW] .../dev_E3_8A_43_0E_F1_2A: Connected=true
[RAW] .../dev_E3_8A_43_0E_F1_2A: ServicesResolved=true
```

Each was followed by a `g_main_context_iteration()` dispatch inside `fu_device_list_wait_for_replug()`, so they land on the context the waiter pumps. But `g-properties-changed` on the `org.bluez.Device1` proxy — and the manager own `interface-proxy-properties-changed` — fired zero times in a 90-second run.

**2. Could the device take longer than 10 seconds?**

No, about 2.8 s (`remove_delay` is 10000 ms):

```
[20:28:37.066] Connected=0 ServicesResolved=0
[20:28:39.307] Connected=1
[20:28:39.842] ServicesResolved=1
```

**3. Does it need re-pairing?**

No. `bluetoothctl` during a manual power cycle:

```
[CHG] Device FE:91:27:7D:CF:44 ServicesResolved: no
[SIGNAL] LE.Disconnected - org.bluez.Reason.Remote, Connection terminated by remote user
[CHG] Device FE:91:27:7D:CF:44 Connected: no
[CHG] Device FE:91:27:7D:CF:44 Connected: yes
[CHG] Device FE:91:27:7D:CF:44 Modalias: usb:v17EFp62F6d0107
[CHG] Device FE:91:27:7D:CF:44 ServicesResolved: yes
```

Paired never changes and there is no DEL entry — the `org.bluez.Device1` object stays present, only its properties change. So `object-added` and `object-removed` legitimately do not fire for a BLE reboot, and detection rests entirely on that one property-changed signal.

## This used to work

I have three older working trees from my earlier PRs (#9760, #10474, #10510). BLE updates succeed there with the same command and an unmodified fwupd core. On current main the same device fails with "device did not come back".

The difference is the main context — bisected to a43aaa18a ("Add fu_context_timeout_add_seconds() that uses the GMainContext for idle"):

| | pre-a43aaa18a | current main |
|---|---|---|
| `fu_bluez_backend_setup()` | `g_main_loop_new(NULL, ...)`, no push_thread_default | `g_main_loop_new(main_ctx, ...)` plus push/pop main_ctx |
| `fu_device_list_wait_for_replug()` | `g_main_context_iteration(NULL, ...)` | `g_main_context_iteration(fu_context_get_main_context(...), ...)` |
| `fu_context_set_main_context()` | never called | `fu-engine-cli.c:4937` |

Before that commit both sides were the global default, so they agreed — which matches your commit message ("it is only by accident"). Now the context is custom and the `org.bluez.Device1` proxy signals no longer reach the waiter.

## What I changed to make it work again

In `fu_bluez_backend_setup()`, subscribe to PropertiesChanged on the manager own connection:

```c
GDBusConnection *conn = g_dbus_object_manager_client_get_connection(
    G_DBUS_OBJECT_MANAGER_CLIENT(self->object_manager));
g_main_context_push_thread_default(main_ctx);
g_dbus_connection_signal_subscribe(conn,
                                   "org.bluez",
                                   "org.freedesktop.DBus.Properties",
                                   "PropertiesChanged",
                                   NULL,
                                   NULL,
                                   G_DBUS_SIGNAL_FLAGS_NONE,
                                   fu_bluez_backend_raw_signal_cb,
                                   self,
                                   NULL);
g_main_context_pop_thread_default(main_ctx);
```

In the callback: filter for `org.bluez.Device1`, look up the interface proxy, copy the changed values in with `g_dbus_proxy_set_cached_property()` (the manager is not updating the cache either, and suitable is computed from it), then call the existing `fu_bluez_backend_object_properties_changed()`.

With that, the full chain completes and the update succeeds:

```
[RAW] ServicesResolved=false -> suitable=0 -> device_removed
[RAW] Connected=true         -> suitable=0
[RAW] ServicesResolved=true  -> suitable=1 -> device_added
BLE setup: ... (second time)
device_list_add ... find_by_id=HIT
clear_wait_for_replug ... remove_source=set
-> install succeeded
```

I expect you would rather fix the context binding properly than carry the manual cache sync, so I have not sent this as a PR. Happy to test any patch, or to submit the workaround as an interim fix if that is useful.

**Comment by hughsie** [comment]
> bisected to https://github.com/fwupd/fwupd/commit/a43aaa18aab374a0e6c9b99455f2e47fe4df81b0

Quality software debugging, thanks for being awesome.

> I expect you would rather fix the context binding properly

The documentation for g_dbus_connection_signal_subscribe() actually has *Note that callback will be invoked in the thread-default main context (see g_main_context_push_thread_default()) of the thread you are calling this method from.* -- so I think using g_main_context_push_thread_default() like you suggested is exactly the right thing to do. Can you do a PR please -- **thanks**!

**Comment by lenovo-li** [comment]
Opened #10870.

One thing worth noting: `g_main_context_push_thread_default()` was already there around the constructor call, so that alone was not the fix. Digging into GLib, the async constructor does not implement `init_async` -- it falls back to the default `GAsyncInitable` implementation:

```c
static void
async_initable_iface_init (GAsyncInitableIface *async_initable_iface)
{
  /* for now, just use default: run GInitable code in thread */
}
```

which runs `::init` in a GTask worker thread (`gasyncinitable.c`, `g_task_run_in_thread`). `subscribe_signals()` is called from `::init`, and `g_task_thread_pool_thread()` does not push any context, so the subscription is bound to the global default context. The push/pop around the async call only affects the context the completion callback runs in.

So the PR constructs the object manager synchronously with the context pushed. That does mean the 1500ms startup timeout from 4a1baae30 can no longer be a `GSource` -- nothing iterates the context while the sync call blocks -- so it cancels from a watchdog thread instead. If you would rather handle that differently, happy to rework it.

No manual cache syncing needed with this approach; `::g-properties-changed` fires normally.
