### PR TITLE
Bind the BlueZ signal subscriptions to the correct GMainContext

### LINKED ISSUE #10862: BLE device not detected after reboot in attach() despite successful reconnection
### Environment
- fwupd version: main branch (5d660d3ea)
- Device: Lenovo BLE mouse (VID 17EF, PID 629A)
- Command: `fwupdtool install <cab> --allow-older`

### Problem
BLE firmware update fails with:
```
failed to attach: failed to wait for attach replug: device 2d9af8a789b80c9891a2578467cc9e77b72c384a did not come back
```

The device successfully reboots and reconnects (confirmed by independent D-Bus monitor), but fwupd doesn't detect it.

### Plugin code
```c
static gboolean
fu_lenovo_accessory_ble_device_attach(FuDevice *device, FuProgress *progress, GError **error)
{
    FuLenovoAccessoryBleDevice *self = FU_LENOVO_ACCESSORY_BLE_DEVICE(device);

    /* release notify_io before device reboot */
    if (self->notify_io != NULL) {
        g_object_unref(self->notify_io);
        self->notify_io = NULL;
    }

    if (!fu_lenovo_accessory_impl_dfu_exit(FU_LENOVO_ACCESSORY_IMPL(device),
                                           FU_LENOVO_ACCESSORY_DFU_EXIT_CODE_DFU_SUCCESS,
                                           error)) {
        g_prefix_error_literal(error, "failed to exit: ");
        return FALSE;
    }
    fu_device_add_flag(device, FWUPD_DEVICE_FLAG_WAIT_FOR_REPLUG);
    return TRUE;
}
```

Device extends `FuBluezDevice`, sets `remove_delay` to 10000 ms in `init()`.

Full code: https://github.com/lenovo-li/fwupd/tree/feature/quirk-configurable-interface/plugins/lenovo-accessory

### Log output

**Coldplug (works):**
```
12:32:24.059 FuBackend BlueZ device /org/bluez/hci0/dev_E3_8A_43_0E_F1_2A: connected=1 paired=1 services_resolved=1 suitable=1
12:32:24.204 FuPluginLenovoAccessory BLE setup: device_id=2d9af8a789b80c9891a2578467cc9e77b72c384a physical_id=/org/bluez/hci0 logical_id=E3:8A:43:0E:F1:2A wait_for_replug=0
```

**Attach (device reboots):**
```
12:33:32.507 FuPluginLenovoAccessory BLE attach: device_id=2d9af8a789b80c9891a2578467cc9e77b72c384a physical_id=/org/bluez/hci0 logical_id=E3:8A:43:0E:F1:2A
12:33:32.521 FuPluginLenovoAccessory BLE attach: dfu_exit sent, device will reboot and reconnect
[10 seconds pass]
failed to attach: failed to wait for attach replug: device did not come back
```

No `BlueZ device` property-changed logs appear after `attach()`, and `BLE setup` is never called a second time.

**External monitor confirms BlueZ sees the reconnection:**
```
[20:28:37.066] Connected=0 ServicesResolved=0
[20:28:39.307] Connected=1
[20:28:39.842] ServicesResolved=1
```

The device returns with the same device_id, physical_id, and logical_id.

### Question
Why doesn't fwupd detect the BLE device after it reboots and reconnects? Is there something specific needed for BLE replug detection that differs from USB?

USB devices in the same plugin work fine with the same `WAIT_FOR_REPLUG` approach.

### PR DESCRIPTION
**Pull request by lenovo-li**
Fixes #10862.

`GDBusObjectManagerClient` subscribes to the bus signals from `::init`, and `g_dbus_connection_signal_subscribe()` binds the subscription to the thread-default main context of the *calling* thread.

The async constructor does not implement `init_async`, so GLib falls back to the default `GAsyncInitable` implementation, which runs `::init` in a GTask worker thread:

```c
static void
async_initable_iface_init (GAsyncInitableIface *async_initable_iface)
{
  /* for now, just use default: run GInitable code in thread */
}
```

That worker thread has no thread-default context, so the subscription ends up bound to the global default context -- which nothing iterates once a custom `GMainContext` is in use. Wrapping the async call in `g_main_context_push_thread_default()` does not help, because that only affects the context the completion callback is invoked in, not the one `::init` runs under.

So no `org.bluez.Device1` `PropertiesChanged` signal was ever dispatched, `::g-properties-changed` never fired, and a BLE device that reboots and reconnects with the same D-Bus object path was never noticed -- `fu_device_list_wait_for_replug()` timed out with `failed to wait for attach replug`.

This regressed in a43aaa18a, before which both the backend and the device list used the global default context, so they agreed.

## The change

Construct the object manager synchronously with the context pushed, so that everything is bound to the context we actually iterate. `libfwupdplugin/fu-bluez-device.c` already constructs its proxies synchronously, so this is consistent with the rest of the BlueZ code.

The startup timeout from 4a1baae30 cannot stay a `GSource` -- nothing would be iterating the context while the sync call blocks -- so it cancels from a watchdog thread instead. The blocking call that can actually hang is `GetManagedObjects`, whose proxy is created inside `::init` and so is not reachable to set a shorter timeout on.

## Testing

Tested on a BLE mouse (`BLUETOOTH\VID_17EF&PID_629A`) which reboots and reconnects after `dfu_exit`:

```
fwupdtool install ../fw/Lenovo-mouse_629a-vs1.0.00.cab --allow-older
...
Successfully installed firmware
```

Also verified the USB path (`USB\VID_17EF&PID_62F5`) still works, and `test-fwupd` passes (145 ok, 0 fail, 2 skipped).

### CODE REVIEW

File: src/fu-bluez-backend.c [hunk 1]
```diff
@@ -179,33 +163,49 @@ fu_bluez_backend_setup(FuBackend *backend,
...
-	helper->cancellable = g_cancellable_new();
-	helper->timeout_source = fu_context_add_timeout(ctx,
-							FU_BLUEZ_BACKEND_TIMEOUT,
-							fu_bluez_backend_timeout_cb,
-							helper);
+	watchdog.cancellable = cancellable;
+	g_mutex_init(&watchdog.mutex);
+	g_cond_init(&watchdog.cond);
+	watchdog_thread =
+	    g_thread_new("fu-bluez-watchdog", fu_bluez_backend_watchdog_thread_cb, &watchdog);
```
Comment (hughsie) [inline src/fu-bluez-backend.c]: I don't follow; why the thread?

Comment (hughsie) [reply src/fu-bluez-backend.c]: Ohh you explained in https://github.com/fwupd/fwupd/issues/10862 -- let me read again.

File: src/fu-bluez-backend.c [hunk 2]
```diff
@@ -129,45 +129,29 @@ fu_bluez_backend_object_removed_cb(GDBusObjectManager *manager,
...
-	GError **error;
 	GCancellable *cancellable;
-	GSource *timeout_source;
-} FuBluezBackendHelper;
-
-static void
-fu_bluez_backend_helper_free(FuBluezBackendHelper *helper)
+	GMutex mutex;
+	GCond cond;
+	gboolean done;
```
Comment (hughsie) [inline src/fu-bluez-backend.c]: it feels like we're re-inventing GCancellable here; can the thread call `g_cancellable_cancel();` to achieve the same thing?

**Comment by hughsie** [comment]
I wonder if it's less complex to run the entire object manager in a thread and just idle-add the events back to the correct main-loop. The other point is maybe the bluez bug that we're trying to work around no longer exists; i.e. maybe we can just remove the cancel callback completely.

**Comment by lenovo-li** [comment]
On the threaded object manager: that looks more invasive rather than less to me. `fu_backend_device_added()` and `fu_backend_device_removed()` both assert `priv->thread_init == g_thread_self()`, so `object-added`, `object-removed` and `g-properties-changed` would all need marshalling back through an idle — three call sites, plus the worker thread and its context to manage, against the current push/pop.

On the cancel: you know the history of those bugs far better than I do, so I'll defer to your call there. If you think it's stale, I'll drop the timeout entirely — that removes the watchdog and leaves just the push/pop around a sync call, which is simpler than what's there today.

Happy to keep digging into either direction with you — let me know which one looks more promising and I'll work it up.

**Comment by lenovo-li** [comment]
Dropped the watchdog in a follow-up commit as suggested -- the object manager is now constructed with a NULL cancellable, leaving just the thread-default context push/pop around the synchronous constructor.

Verified on real hardware with a BLE mouse (Lenovo, 0x629a), which is the case that originally hit the missed-signal hang. Both directions work:

- upgrade to vs1.0.00: `Successfully installed firmware`
- downgrade to vs0.0.18: `Successfully installed firmware`

No startup hang observed with the watchdog gone, so the bluez behaviour it worked around does seem to be fixed these days.

File: src/fu-bluez-backend.c [hunk 3]
```diff
@@ -179,33 +135,29 @@ fu_bluez_backend_setup(FuBackend *backend,
...
-						 "/",
-						 NULL,
-						 NULL,
-						 NULL,
-						 helper->cancellable,
-						 fu_bluez_backend_connect_cb,
-						 helper);
+	self->object_manager =
+	    g_dbus_object_manager_client_new_for_bus_sync(G_BUS_TYPE_SYSTEM,
+							  G_DBUS_OBJECT_MANAGER_CLIENT_FLAGS_NONE,
```
Comment (hughsie) [inline src/fu-bluez-backend.c]: I do wonder if G_DBUS_OBJECT_MANAGER_CLIENT_FLAGS_DO_NOT_AUTO_START would solve the problem here; i.e. if bluez isn't already started then this function won't block if bluez has wedged during startup. Would that work for you?

**Comment by lenovo-li** [comment]
Good call -- DO_NOT_AUTO_START works. Pushed as a follow-up commit.

It sets G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START on the control proxy, so the bus won't try to activate a wedged bluez, and when there's no name owner initable_init() skips the GetManagedObjects call entirely. plugins/modem-manager/fu-mm-backend.c already pairs the same flag with a sync constructor.

Tested both paths: with bluez running startup discovers BLE devices normally; with bluetoothd stopped startup completes without blocking. BLE mouse firmware operations (0x629a upgrade + downgrade) work.

**Comment by hughsie** [comment]
can you squash down to one commit please, then force push. Then LGTM -- thanks.

**Review by hughsie — APPROVED** [review]
